name: planifago
description: Planifago application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  graphql_flutter: ^4.0.0-beta
  jwt_decoder: ^1.0.4
  hive: ^1.4.4+1  
  flutter_dotenv: ^3.1.0
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  provider: ^4.3.3

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env